"""grad attributes

Revision ID: 048855b07cc4
Revises: 1609185700ac
Create Date: 2018-03-25 10:34:16.436527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048855b07cc4'
down_revision = '1609185700ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summative_assessment', sa.Column('academic_excellence', sa.Integer(), nullable=True))
    op.add_column('summative_assessment', sa.Column('active_citizenship', sa.Integer(), nullable=True))
    op.add_column('summative_assessment', sa.Column('critical_thinking', sa.Integer(), nullable=True))
    op.add_column('summative_assessment', sa.Column('learning_personal_development', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summative_assessment', 'learning_personal_development')
    op.drop_column('summative_assessment', 'critical_thinking')
    op.drop_column('summative_assessment', 'active_citizenship')
    op.drop_column('summative_assessment', 'academic_excellence')
    # ### end Alembic commands ###
