"""empty message

Revision ID: 1609185700ac
Revises: 9d06f3ed7de3
Create Date: 2018-03-22 12:13:58.410711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1609185700ac'
down_revision = '9d06f3ed7de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('attendance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'attendance')
    # ### end Alembic commands ###
