"""empty message

Revision ID: 22ae97aabab6
Revises: a24d6fe039ee
Create Date: 2018-02-10 15:09:24.556484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ae97aabab6'
down_revision = 'a24d6fe039ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formative_assessment', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'formative_assessment', 'course', ['course_id'], ['id'])
    op.add_column('summative_assessment', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'summative_assessment', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summative_assessment', type_='foreignkey')
    op.drop_column('summative_assessment', 'course_id')
    op.drop_constraint(None, 'formative_assessment', type_='foreignkey')
    op.drop_column('formative_assessment', 'course_id')
    # ### end Alembic commands ###
