"""programme table

Revision ID: 23a434ec17ee
Revises: 68b9d6a2aefa
Create Date: 2018-02-06 11:29:30.316169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a434ec17ee'
down_revision = '68b9d6a2aefa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student', sa.Column('programme_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'programme', ['programme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'programme_id')
    op.drop_table('programme')
    # ### end Alembic commands ###
