"""empty message

Revision ID: 2835da95262c
Revises: a3f9317d7dcc
Create Date: 2018-02-10 13:56:44.507931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2835da95262c'
down_revision = 'a3f9317d7dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ProgrammeCourses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProgrammeCourses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ProgrammeCourses_id_seq"\'::regclass)'), nullable=False),
    sa.Column('programme_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='ProgrammeCourses_course_id_fkey'),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name='ProgrammeCourses_programme_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ProgrammeCourses_pkey')
    )
    op.drop_table('programme_courses')
    # ### end Alembic commands ###
