"""empty message

Revision ID: 4ae441195f51
Revises: 6cb99418b891
Create Date: 2018-03-02 10:50:56.789398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae441195f51'
down_revision = '6cb99418b891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'year')
    # ### end Alembic commands ###
