"""empty message

Revision ID: 53702e04ecbe
Revises: 22ae97aabab6
Create Date: 2018-02-10 19:10:00.239793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53702e04ecbe'
down_revision = '22ae97aabab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formative_assessment', 'submitted')
    op.drop_column('formative_assessment', 'cgs')
    op.add_column('student_formative_assessments', sa.Column('cgs', sa.Integer(), nullable=True))
    op.add_column('student_formative_assessments', sa.Column('submitted', sa.Integer(), nullable=True))
    op.add_column('student_summative_assessments', sa.Column('cgs', sa.Integer(), nullable=True))
    op.add_column('student_summative_assessments', sa.Column('submitted', sa.Integer(), nullable=True))
    op.drop_column('summative_assessment', 'submitted')
    op.drop_column('summative_assessment', 'cgs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summative_assessment', sa.Column('cgs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('summative_assessment', sa.Column('submitted', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('student_summative_assessments', 'submitted')
    op.drop_column('student_summative_assessments', 'cgs')
    op.drop_column('student_formative_assessments', 'submitted')
    op.drop_column('student_formative_assessments', 'cgs')
    op.add_column('formative_assessment', sa.Column('cgs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('formative_assessment', sa.Column('submitted', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
