"""empty message

Revision ID: 55607abd007b
Revises: dedeb549cf11
Create Date: 2018-02-20 11:50:16.930581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55607abd007b'
down_revision = 'dedeb549cf11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'course_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'course_name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###
