"""empty message

Revision ID: 7d680c74ba28
Revises: 89c1b43b8dd0
Create Date: 2018-02-10 14:01:25.002500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d680c74ba28'
down_revision = '89c1b43b8dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_formative_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('formative_assessment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formative_assessment_id'], ['formative_assessment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('StudentFormativeAssessments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StudentFormativeAssessments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"StudentFormativeAssessments_id_seq"\'::regclass)'), nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('formative_assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['formative_assessment_id'], ['formative_assessment.id'], name='StudentFormativeAssessments_formative_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='StudentFormativeAssessments_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='StudentFormativeAssessments_pkey')
    )
    op.drop_table('student_formative_assessments')
    # ### end Alembic commands ###
