"""student f_assessment m2m

Revision ID: a3f9317d7dcc
Revises: 05b794b0b9a0
Create Date: 2018-02-10 13:51:27.434620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f9317d7dcc'
down_revision = '05b794b0b9a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProgrammeCourses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('programme_courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programme_courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('programme_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='programme_courses_course_id_fkey'),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name='programme_courses_programme_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='programme_courses_pkey')
    )
    op.drop_table('ProgrammeCourses')
    # ### end Alembic commands ###
