"""empty message

Revision ID: d53873408855
Revises: 01d03048ccc2
Create Date: 2018-03-13 09:26:09.191057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53873408855'
down_revision = '01d03048ccc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_summative_assessments', 'submitted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_summative_assessments', sa.Column('submitted', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
