"""add grad attributes

Revision ID: d866b45514db
Revises: 1609185700ac
Create Date: 2018-03-24 18:25:33.130859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd866b45514db'
down_revision = '1609185700ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summative_assessment', sa.Column('academic_skills', sa.Float(), nullable=True))
    op.add_column('summative_assessment', sa.Column('it_skills', sa.Float(), nullable=True))
    op.add_column('summative_assessment', sa.Column('library_skills', sa.Float(), nullable=True))
    op.add_column('summative_assessment', sa.Column('professional_skills', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summative_assessment', 'professional_skills')
    op.drop_column('summative_assessment', 'library_skills')
    op.drop_column('summative_assessment', 'it_skills')
    op.drop_column('summative_assessment', 'academic_skills')
    # ### end Alembic commands ###
