"""changes to course

Revision ID: dedeb549cf11
Revises: 112c7ba9b427
Create Date: 2018-02-20 11:38:28.351054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedeb549cf11'
down_revision = '112c7ba9b427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('credits', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'level')
    op.drop_column('course', 'credits')
    # ### end Alembic commands ###
